### ISSUE TITLE
fastfetch has moved to  glibc 2.35 and changed release naming

### ISSUE THREAD

**Issue by philclifford** [wimpysworld/deb-get#1008]
latest release no longer matches pattern
older releases can be used for older OS releases ( <= focal/bullseye ) until debs build with a compatible glibc are found
The latest release also has an `aarch64` release and adds support for Asahi2, z/OS, Tatra, PikaOS.

**Comment by mralusw** [comment]
There's also a renaming problem, the repo is now `fastfetch-cli/fastfetch`. Though I think LinusDierheimer/fastfetch redirects.

The main problem for me though is that I can't run `deb-get update`, as it chokes with `ERROR! Missing required information of github package fastfetch:` (and also `croc`). If I change `/etc/deb-get/01-main.d/fastfetch`, it reverts back from deb-get repo &mdash; and fails of course. I forgot how to bypass the auto-revert-to-official mechanism

**Comment by philclifford** [comment]
Thanks @mralusw. I didn't notice the redirect so I'll amend the repo in the PR. You can drop the fixed definition into `/etc/deb-get/99-local.d/` (and remember to remove it later when a fix is merged). Or you can add an external repo with a fix. That could be one you maintain (i.e. create a branch on your own fork and add fixes to that branch then add a repo definition to pull that to override 01-main definitions) or you could use my `extras` branch

```
echo "https://raw.githubusercontent.com/philclifford/deb-get/extras/91-fixes" |sudo tee /etc/deb-get/91-fixes.repo
```

You need to remove the "broken" cache files then update, but that should override the broken definitions until main is fixed.  Then you or I need to remove the overrides.

The third option is to submit a PR which I can merge (I cannot merge my own work).

**Comment by mralusw** [comment]
Thanks @philclifford . The override-repo approach seems better. I guess it's documented in the main README. I wonder if I can drop overrides that completely disable annoying packages, by setting some vars to null. I've worked on deb-get before, but I forgot the intricacies of the update process.

**Comment by philclifford** [comment]
The `99-local.d` allows to re-define a definition, but as that repo doesn't have a manifest it doesn't permit "deprecating" an app. You could supply a definition that says an app is not supported on your OS/architecture if you want to banish it to `--include-unsupported` lists and prevent updating or installing the app.  You can "deprecate" with an override in an external repo by commenting it in the manifest. External repos are the best solution for fixing definition bugs, testing contributions, adding unsupported applications (pending contributions for example) or tweaking definitions (I always install  the extended version of `hugo` for example).  They are documented in the main readme https://github.com/wimpysworld/deb-get/blob/main/README.md#adding-software and https://github.com/wimpysworld/deb-get/blob/main/EXTREPO.md

As noted above the `extras` branch of my fork has a few that I use which include pending fixes, pending contributions etc .

**Comment by bshor** [comment]
Hi -- fastfetch is still broken for installing. Is this right?

**Comment by philclifford** [comment]
Until #1007 is merged, yes @bshor it is broken unless you use the PR version of the definition as an override or add a fixed external repo override as explained above.
